# Generated by Django 3.1.5 on 2021-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherId', models.AutoField(primary_key=True, serialize=False)),
                ('TeacherFName', models.CharField(max_length=100)),
                ('TeacherLName', models.CharField(max_length=100)),
                ('TeacherEmail', models.CharField(max_length=100)),
                ('TeacherPhone', models.CharField(max_length=100)),
                ('TeacherRoomNo', models.CharField(max_length=100)),
                ('TeacherSubjectsTaught', models.CharField(max_length=100)),
                ('PhotoFileName', models.DateField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
