# Generated by Django 3.1.5 on 2021-01-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0003_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='PhotoFileName',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
