# Generated by Django 3.1.5 on 2021-01-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0004_auto_20210125_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='PhotoFileName',
            field=models.CharField(max_length=100),
        ),
    ]
