# Generated by Django 3.1.5 on 2021-01-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0005_auto_20210125_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='PhotoFileName',
            field=models.ImageField(upload_to='images'),
        ),
    ]
